version: "3.8"
services:
  db:
    # Usamos la imagen oficial de MySQL
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=api_tv  # Nombre de la base de datos a crear
      - MYSQL_ROOT_PASSWORD=root_password  # Contraseña del root
      - MYSQL_USER=admin  # Nombre de usuario
      - MYSQL_PASSWORD=admin_password  # Contraseña del usuario admin
    ports:
      - 3306:3306  # Exponemos el puerto 3306 para acceso
    volumes:
      - tvision_mysql_data:/var/lib/mysql  # Volumen persistente para los datos de MySQL
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - main

networks:
  main:

volumes:
  tvision_mysql_data:
