services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=api_tv
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin_password
    ports:
      - 3306:3306
    command:
      --require-secure-transport=OFF
    volumes:
      - tvision_mysql_data:/var/lib/mysql
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - main

  app:
    build:
      context: .
    volumes:
      - .:/app 
    ports:
      - 8000:8000
    depends_on:
      - db  
    networks:
      - main
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=api_tv
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin_password
    command: /entrypoint.sh

networks:
  main:
    external: true
    name: mana_rest_main

volumes:
  tvision_mysql_data:
