# Generated by Django 4.2.15 on 2025-03-05 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stores', through='restaurant.StoreUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.store'),
        ),
        migrations.AddField(
            model_name='banquetitem',
            name='banquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.banquet'),
        ),
        migrations.AddField(
            model_name='banquetitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food'),
        ),
        migrations.AddField(
            model_name='banquet',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store'),
        ),
        migrations.AddField(
            model_name='banquet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
