# Generated by Django 4.2.15 on 2024-08-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='foods',
            field=models.ManyToManyField(through='restaurant.TicketItem', to='restaurant.food'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='restaurant.store'),
        ),
    ]
