# Generated by Django 4.2.15 on 2024-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_ticket_ticketitem_ticket_foods_ticket_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='foods',
        ),
        migrations.AddField(
            model_name='store',
            name='foods',
            field=models.ManyToManyField(to='restaurant.food'),
        ),
    ]
