# Generated by Django 4.2.15 on 2024-08-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_store_user_store_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='Store', max_length=20, null=True),
        ),
    ]
