# Generated by Django 4.2.15 on 2024-08-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_store_foods_food_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total',
        ),
    ]
