# Generated by Django 4.2.15 on 2024-08-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_ticket_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
