# Generated by Django 4.2.15 on 2024-09-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uow', '0001_initial'),
        ('restaurant', '0010_ticket_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guests', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='BanqueteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.banquet')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
            ],
        ),
        migrations.AddField(
            model_name='banquet',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store'),
        ),
        migrations.AddField(
            model_name='banquet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uow.userprofile'),
        ),
    ]
