# Generated by Django 4.2.15 on 2024-09-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_banqueteitem_banquetitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banquetitem',
            old_name='banquete',
            new_name='banquet',
        ),
    ]
