# Generated by Django 4.2.15 on 2024-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_ticketitem_discount_food_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount as a percentage (0 to 100)', max_digits=5),
        ),
    ]
