# Generated by Django 4.2.15 on 2024-11-27 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0015_alter_food_category_alter_food_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount as a percentage (0 to 100%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Enter a valid phone number format, e.g., +123456789.', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stores', through='restaurant.StoreUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
